services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    depends_on:
      - qdrant
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  qdrant_storage:
